// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0fX6T8Lfo-vYk6Xmu-1qx19rcsuellY',
    appId: '1:827130332246:web:6b315580bb17ee517ba7f7',
    messagingSenderId: '827130332246',
    projectId: 'evaly-488b4',
    authDomain: 'evaly-488b4.firebaseapp.com',
    storageBucket: 'evaly-488b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4yqRqeSJ347hIgoyClkO55Ttyepg8Zk',
    appId: '1:827130332246:android:92fca1216d662bb97ba7f7',
    messagingSenderId: '827130332246',
    projectId: 'evaly-488b4',
    storageBucket: 'evaly-488b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvCjzvM6ycZikSBoME55HXvz3l9K6nTlU',
    appId: '1:827130332246:ios:72d11fbf819317637ba7f7',
    messagingSenderId: '827130332246',
    projectId: 'evaly-488b4',
    storageBucket: 'evaly-488b4.appspot.com',
    iosBundleId: 'com.example.evaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvCjzvM6ycZikSBoME55HXvz3l9K6nTlU',
    appId: '1:827130332246:ios:72d11fbf819317637ba7f7',
    messagingSenderId: '827130332246',
    projectId: 'evaly-488b4',
    storageBucket: 'evaly-488b4.appspot.com',
    iosBundleId: 'com.example.evaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt0fX6T8Lfo-vYk6Xmu-1qx19rcsuellY',
    appId: '1:827130332246:web:413155f54e91d50b7ba7f7',
    messagingSenderId: '827130332246',
    projectId: 'evaly-488b4',
    authDomain: 'evaly-488b4.firebaseapp.com',
    storageBucket: 'evaly-488b4.appspot.com',
  );
}
